name: Create Azure Resources

on:
  push:
    paths:
      - 'bicep/**'
      - 'github/workflows/createAzureResources.yml'

  workflow_dispatch:

env:
  LOCATION: 'eastus'
  DEPLOYMENT_NAME: 'ai-magic-demo'

jobs:
  create-resources:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
            
      - name: Deploy Azure Resources
        id: createResources
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.SUBSCRIPTION_ID }}
          scope: subscription
          region: ${{ env.LOCATION }}
          template: ./bicep/main.bicep     
          
      - uses: gliech/create-github-secret-action@v1
        name: Write function app name
        with:
          name: FUNCTIONAPP_NAME
          value: ${{ steps.createResources.outputs.functionName }}
          pa_token: ${{ secrets.PA_TOKEN }}            
        